# Generated by Django 6.0.2 on 2026-02-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('exam_tip', 'Exam Tip'), ('wellness_guide', 'Wellness Guide')], max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('content_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(default='English', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
