# Generated by Django 6.0.2 on 2026-02-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='language',
            field=models.CharField(default='English', max_length=30),
        ),
    ]
