# Generated by Django 6.0.2 on 2026-02-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'community_post',
                'ordering': ['-created_at'],
            },
        ),
    ]
