# Generated by Django 6.0.2 on 2026-02-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_at_risk',
            field=models.BooleanField(default=False),
        ),
    ]
